# Attach to emacs server with new frame
alias emacs='emacsclient -a emacs -c'

# Attach to emacs server using existing frame
alias emacsd='emacsclient -a emacs -n'

# Create new instance of emacs
alias emacsp='command emacs'

# Print symbolic and octal file mode
alias mode='stat -c "%A %U %G (%a) %n"'

# Quick way to run django test server
alias mrs='python manage.py runserver'

# Enable ANSI color for ri
alias ri="ri -f ansi"

# Rails shortcuts
alias rt="rake test"
alias rtf="rake test:functionals"
alias rtu="rake test:units"
alias rti="rake test:integration"
alias rtb="rake test:benchmark"

# Print a list of listening ports
alias ports="sudo netstat -pln"

# tmux
alias tmux="tmux -2"

# cd shortcuts
alias cdf="cd ~/dev/dotfiles"
alias cv="cd ~/.vim"
alias c..="cd .."

# git shortcuts
alias gs="git status"
alias gcom="git commit"
alias gcoma="git commit -a"
alias gdf="git diff"
alias gpush="git push"
