# Print symbolic and octal file mode
alias mode='stat -c "%A %U %G (%a) %n"'

# Quick way to run django test server
alias mrs='python manage.py runserver'

# Enable ANSI color for ri
alias ri="ri -f ansi"

# Rails shortcuts
alias rt="rake test"
alias rtb="rake test:benchmark"
alias rtf="rake test:functionals"
alias rti="rake test:integration"
alias rtu="rake test:units"

# Print a list of listening ports
alias ports="sudo netstat -pln"

# tmux
alias tmux="tmux -2"

# cd shortcuts
alias cdf="cd ~/dev/dotfiles"
alias cv="cd ~/.vim"
alias c..="cd .."

# git shortcuts
alias gcom="git commit"
alias gcoma="git commit -a"
alias gdf="git diff"
alias gpull="git pull"
alias gpush="git push"
alias gs="git status"

# Udemy stuff
alias env_website_django='source ~/.virtualenvs/udemy/bin/activate'
alias db_tunnel='ssh -fNg -p2022 -L 3333:vm1:3306 bahaddin@infra1.udemy.com'
alias db_tunnel_kill='kill $(sudo lsof -t -i:3333)'
alias db_tunnel4='ssh -fNg -p2022 -L 3334:localhost:3306 bahaddin@infra1.udemy.com'
alias db_tunnel4_kill='kill $(sudo lsof -t -i:3334)'
alias udemy_test_unit='./manage.py test --settings=udemy.settings.test_unit --processes=8'
alias udemy_test_integration='./manage.py test --settings=udemy.settings.test_integration --processes=1'
alias udemy_test_cover='./manage.py test --settings=udemy.settings.test_coverage'
alias udemy_shell_plus='./manage.py shell_plus --settings=udemy.settings.local'
alias udemy_runserver='./manage.py runserver 8000'
alias udemy_killserver='kill $(sudo lsof -t -i:8000)'
alias udemy_local_setup="cd ~/dev/udemy-django/static/; npm install; ./node_modules/.bin/grunt; ./node_modules/.bin/grunt less:v4; cd -; cd ~/dev/udemy-django/; ./manage.py collectstatic; cd -;"
alias elastic_tunnel='ssh -fNg -p2022 -L 9200:10.1.0.104:9200 murataydos@infra1.udemy.com'
alias elastic_tunnel_kill='kill $(sudo lsof -t -i:9200)'
