# Print symbolic and octal file mode
alias mode='stat -c "%A %U %G (%a) %n"'

# Quick way to run django test server
alias mrs='python manage.py runserver'

# Enable ANSI color for ri
alias ri="ri -f ansi"

# Rails shortcuts
alias rt="rake test"
alias rtb="rake test:benchmark"
alias rtf="rake test:functionals"
alias rti="rake test:integration"
alias rtu="rake test:units"

# Print a list of listening ports
alias ports="sudo netstat -pln"

# tmux
alias tmux="tmux -2"

# cd shortcuts
alias cdf="cd ~/dev/dotfiles"
alias cv="cd ~/.vim"
alias c..="cd .."

# git shortcuts
alias gcom="git commit"
alias gcoma="git commit -a"
alias gdf="git diff"
alias gpull="git pull"
alias gpush="git push"
alias gs="git status"
